(function () {
  "use strict";
  var state = { services: [], resources: [], engagements: [], inquiries: [] };
  var statusLine = document.getElementById("admin-status");
  var engagementTransitions = { pending: ["scoping", "cancelled"], scoping: ["active", "cancelled"], active: ["completed", "cancelled"], completed: [], cancelled: [] };
  var invoiceTransitions = { not_issued: ["outstanding", "cancelled"], outstanding: ["paid", "cancelled"], paid: [], cancelled: [] };
  function el(tag, className, text) { var node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; }
  function cell(label, content) { var td = el("td"); td.dataset.label = label; if (content instanceof Node) td.appendChild(content); else td.textContent = content; return td; }
  function rowHead(text) { var th = el("th", "table__row-head", String(text)); th.scope = "row"; return th; }
  function money(value) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
  function date(value) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
  function announce(message, isError) { statusLine.textContent = message; statusLine.classList.toggle("form-message--error", Boolean(isError)); }
  function actions(buttons) { var group = el("div", "table__actions"); buttons.forEach(function (config) { var button = el("button", "btn btn--sm " + (config.danger ? "btn--danger" : "btn--ghost"), config.label); button.type = "button"; button.addEventListener("click", config.run); group.appendChild(button); }); return group; }
  function formObject(form) { var data = Object.fromEntries(new FormData(form).entries()); form.querySelectorAll('input[type="checkbox"]').forEach(function (box) { data[box.name] = box.checked; }); return data; }
  function openForm(form, record) { form.reset(); form.hidden = false; if (record) Object.keys(record).forEach(function (key) { var field = form.elements[key]; if (!field) return; if (field.type === "checkbox") field.checked = Boolean(record[key]); else field.value = record[key] ?? ""; }); form.scrollIntoView({ behavior: "smooth", block: "start" }); }
  function closeForm(form) { form.reset(); form.hidden = true; }

  function renderServices() { var tbody = document.querySelector("#admin-services-table tbody"); tbody.replaceChildren(); state.services.forEach(function (item) { var tr = document.createElement("tr"); tr.append(rowHead(item.service_id), cell("Name", item.name), cell("Category", item.category), cell("Price", money(item.base_price)), cell("State", item.is_active ? "active" : "inactive"), cell("Actions", actions([{ label: "Edit", run: function () { openForm(document.getElementById("service-form"), item); } }, { label: "Delete", danger: true, run: function () { removeRecord("services", item.service_id, item.name); } }]))); tbody.appendChild(tr); }); }
  function renderResources() { var tbody = document.querySelector("#admin-vault-table tbody"); tbody.replaceChildren(); state.resources.forEach(function (item) { var tr = document.createElement("tr"); tr.append(rowHead(item.resource_id), cell("Title", item.title), cell("Category", item.category), cell("Published", String(item.published_at).slice(0, 10)), cell("State", item.is_published ? "published" : "draft"), cell("Actions", actions([{ label: "Edit", run: function () { openForm(document.getElementById("resource-form"), { ...item, published_at: String(item.published_at).slice(0, 10) }); } }, { label: "Delete", danger: true, run: function () { removeRecord("resources", item.resource_id, item.title); } }]))); tbody.appendChild(tr); }); }
  function renderEngagements() { var tbody = document.querySelector("#admin-engagements-table tbody"); tbody.replaceChildren(); state.engagements.forEach(function (item) { var tr = document.createElement("tr"); tr.append(rowHead(item.reference_code), cell("Client", item.company_name + " · " + item.client_name), cell("Service", item.service_name), cell("Requested slot", date(item.requested_start_at)), cell("Status", el("span", "badge badge--" + item.status, item.status)), cell("Actions", actions([{ label: "View", run: function () { openEngagement(item.reference_code); } }]))); tbody.appendChild(tr); }); }
  function renderInquiries() { var tbody = document.querySelector("#admin-inquiries-table tbody"); tbody.replaceChildren(); state.inquiries.forEach(function (item) { var tr = document.createElement("tr"); var select = el("select", "select select--inline"); ["new", "reviewed", "closed"].forEach(function (value) { var option = el("option", null, value); option.value = value; option.selected = value === item.status; select.appendChild(option); }); select.setAttribute("aria-label", "Status for inquiry from " + item.company_name); select.addEventListener("change", async function () { try { await ORLApi.request("/api/admin/inquiries/" + item.inquiry_id + "/status", { method: "PATCH", body: { status: select.value } }); await loadInquiries(); announce("Inquiry updated."); } catch (error) { announce(error.message, true); } }); tr.append(rowHead(date(item.created_at)), cell("Contact", item.full_name + " · " + item.email), cell("Company", item.company_name), cell("Message", item.message), cell("Status", select), cell("Actions", actions([{ label: "Delete", danger: true, run: function () { removeInquiry(item); } }]))); tbody.appendChild(tr); }); }

  async function saveForm(event, type) { event.preventDefault(); var form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } var value = formObject(form); var idName = type === "services" ? "service_id" : "resource_id"; var id = value[idName]; delete value[idName]; var url = "/api/admin/" + type + (id ? "/" + id : ""); try { await ORLApi.request(url, { method: id ? "PUT" : "POST", body: value }); closeForm(form); await (type === "services" ? loadServices() : loadResources()); announce((type === "services" ? "Service" : "Resource") + " saved."); } catch (error) { ORLApi.applyFieldErrors(form, error.fields); announce(error.message, true); } }
  async function removeRecord(type, id, label) { if (!confirm("Delete " + label + "?")) return; try { await ORLApi.request("/api/admin/" + type + "/" + id, { method: "DELETE" }); await (type === "services" ? loadServices() : loadResources()); announce("Record deleted."); } catch (error) { announce(error.message, true); } }
  async function removeInquiry(item) { if (!confirm("Delete the inquiry from " + item.company_name + "?")) return; try { await ORLApi.request("/api/admin/inquiries/" + item.inquiry_id, { method: "DELETE" }); await loadInquiries(); announce("Inquiry deleted."); } catch (error) { announce(error.message, true); } }
  async function loadServices() { state.services = (await ORLApi.request("/api/admin/services")).data; renderServices(); }
  async function loadResources() { state.resources = (await ORLApi.request("/api/admin/resources")).data; renderResources(); }
  async function loadEngagements() { state.engagements = (await ORLApi.request("/api/admin/engagements")).data; renderEngagements(); }
  async function loadInquiries() { state.inquiries = (await ORLApi.request("/api/admin/inquiries")).data; renderInquiries(); }
  function addPair(dl, label, value) { var dt = el("dt", null, label); var dd = el("dd", null, value); dl.append(dt, dd); }
  function options(select, values, selected) { select.replaceChildren(); if (!values.length) { var terminal = el("option", null, "No further transitions"); terminal.value = selected; select.appendChild(terminal); select.disabled = true; return; } select.disabled = false; values.forEach(function (value) { var option = el("option", null, value); option.value = value; select.appendChild(option); }); }
  async function openEngagement(reference) { try { var item = (await ORLApi.request("/api/admin/engagements/" + encodeURIComponent(reference))).data; var panel = document.getElementById("admin-engagement-detail"); document.getElementById("admin-detail-reference").textContent = item.reference_code; document.getElementById("admin-detail-title").textContent = item.service_name + " for " + item.company_name; document.getElementById("admin-detail-scope").textContent = item.scope_description; var summary = document.getElementById("admin-detail-summary"); summary.replaceChildren(); addPair(summary, "Client", item.client_name + " · " + item.client_email); addPair(summary, "Requested start", date(item.requested_start_at)); addPair(summary, "Current status", item.status); addPair(summary, "Billing", item.billing_method.replace("_", " ") + " · " + item.invoice_status); var targets = document.getElementById("admin-detail-targets"); targets.replaceChildren(); item.targets.forEach(function (target) { targets.appendChild(el("li", null, target.target_value)); }); var statusForm = document.getElementById("engagement-status-form"); statusForm.elements.reference.value = item.reference_code; options(statusForm.elements.status, engagementTransitions[item.status], item.status); statusForm.querySelector('button[type="submit"]').disabled = !engagementTransitions[item.status].length; var invoiceForm = document.getElementById("invoice-form"); invoiceForm.elements.reference.value = item.reference_code; invoiceForm.elements.amount.value = item.invoice_amount; options(invoiceForm.elements.status, invoiceTransitions[item.invoice_status].concat(item.invoice_status), item.invoice_status); invoiceForm.elements.status.value = item.invoice_status; document.getElementById("authorization-download").href = "/api/admin/engagements/" + encodeURIComponent(item.reference_code) + "/authorization"; panel.hidden = false; panel.scrollIntoView({ behavior: "smooth", block: "start" }); } catch (error) { announce(error.message, true); } }
  async function updateStatus(event) { event.preventDefault(); var value = formObject(event.currentTarget); try { await ORLApi.request("/api/admin/engagements/" + encodeURIComponent(value.reference) + "/status", { method: "PATCH", body: { status: value.status, note: value.note } }); await loadEngagements(); await openEngagement(value.reference); announce("Engagement status updated."); } catch (error) { announce(error.message, true); } }
  async function updateInvoice(event) { event.preventDefault(); var value = formObject(event.currentTarget); try { await ORLApi.request("/api/admin/engagements/" + encodeURIComponent(value.reference) + "/invoice", { method: "PATCH", body: { status: value.status, amount: value.amount } }); await loadEngagements(); await openEngagement(value.reference); announce("Invoice updated."); } catch (error) { announce(error.message, true); } }
  async function init() { if (!(await ORLApi.guard("admin"))) return; document.querySelector('[data-open-form="service"]').addEventListener("click", function () { openForm(document.getElementById("service-form")); }); document.querySelector('[data-open-form="resource"]').addEventListener("click", function () { openForm(document.getElementById("resource-form")); }); document.querySelectorAll("[data-cancel-form]").forEach(function (button) { button.addEventListener("click", function () { closeForm(button.closest("form")); }); }); document.querySelector("[data-close-detail]").addEventListener("click", function () { document.getElementById("admin-engagement-detail").hidden = true; }); document.getElementById("service-form").addEventListener("submit", function (event) { saveForm(event, "services"); }); document.getElementById("resource-form").addEventListener("submit", function (event) { saveForm(event, "resources"); }); document.getElementById("engagement-status-form").addEventListener("submit", updateStatus); document.getElementById("invoice-form").addEventListener("submit", updateInvoice); try { await Promise.all([loadServices(), loadResources(), loadEngagements(), loadInquiries()]); announce(state.services.length + " services, " + state.engagements.length + " engagements, " + state.inquiries.length + " inquiries, and " + state.resources.length + " resources loaded."); } catch (error) { announce(error.message, true); } }
  init();
})();
